CREATE TABLE IF NOT EXISTS categories (id INTEGER NOT NULL PRIMARY KEY, category TEXT NOT NULL);

INSERT INTO categories (category) VALUES
('White'), 
('Strong'),
('Tall'),
('Such Slut'),
('Skinny'),
('Stupid'),
('Ugly'),
('Cross Eyed'),
('Short'),
('Old'),
('Hunchbacked'),
('Nasty'),
('Lazy'),
('House Small'),
('Hairy'),
('Hair Nappy'),
('Greasy'),
('Glasses Thick'),
('Ghetto'),
('Flat'),
('Fat'),
('Dirty'),
('Bald'),
('Dumb'),
('Dark'),
('Butch'),
('Black'),
('Math'),
('Dirty Nasty Greasy'),
('Nerd Geek'),
('Dumb Stupid'),
('Poor'),
('Anime'),
('Harry Potter'),
('Star Trek Wars Science Fiction Nerds'),
('Barack Obama'),
('Miscellaneous');

