CREATE TABLE IF NOT EXISTS categories (id INTEGER NOT NULL PRIMARY KEY, category TEXT NOT NULL);

INSERT INTO categories (category) VALUES
('Anime'),
('Bald'),
('Barack Obama'),
('Black'),
('Butch'),
('Dark'),
('Dirty'),
('Dirty Nasty Greasy'),
('Dumb'),
('Dumb Stupid'),
('Cross Eyed'),
('Fat'),
('Flat'),
('Ghetto'),
('Glasses Thick'),
('Greasy'),
('Hair Nappy'),
('Hairy'),
('Harry Potter'),
('House Small'),
('Hunchbacked'),
('Lazy'),
('Miscellaneous'),
('Math'),
('Nasty'),
('Nerd Geek'),
('Old'),
('Strong'),
('Poor'),
('Short'),
('Skinny'),
('Star Trek Wars Science Fiction Nerds'),
('Stupid'),
('Such Slut'),
('Tall'),
('Ugly'),
('White');
